### ISSUE TITLE
HttpSocket issue with Cake version 2.3

### ISSUE THREAD

**Issue by ryantology** [josegonzalez/cakephp-elastic-search-datasource#11]
I tried to upgrade to cakephp 2.3 today and noticed a number of warnings against httpsocket and elasticsource. I posted the issue against Cakephp for the commit that changed in httpsocket. https://github.com/cakephp/cakephp/commit/240c8718ebb92389ed32fb303777e4d289eb7ebc#commitcomment-2461636

I was wondering if anyone had seen this issue yet before I dig deeper into the fix.

**Comment by josegonzalez** [comment]
Closed by 1795b2e409bf0a34fe06d3e7df813d6676a93023.
