### ISSUE TITLE
php strict warnings

### ISSUE THREAD

**Issue by burzum** [josegonzalez/cakephp-elastic-search-datasource#13]
Strict (2048): Declaration of ElasticSource::listSources() should be compatible with DataSource::listSources($data = NULL) [APP\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1705]

Strict (2048): Declaration of ElasticSource::describe() should be compatible with DataSource::describe($model) [APP\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1705]

Strict (2048): Declaration of ElasticSource::read() should be compatible with DataSource::read(Model $model, $queryData = Array, $recursive = NULL) [APP\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1705]

Strict (2048): Declaration of ElasticSource::update() should be compatible with DataSource::update(Model $model, $fields = NULL, $values = NULL, $conditions = NULL) [APP\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1705]

**Comment by josegonzalez** [comment]
Closed by e062b69d38a1947da10ac7b830ff6a399676f57a
