### ISSUE TITLE
Conditions not combining correctly... query bypass

### ISSUE THREAD

**Issue by zeroasterisk** [josegonzalez/cakephp-elastic-search-datasource#20]
I am unable to mix and match conditions in any way that works...

## Document in the index

		{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":0.2936909,"hits":[{"_index":"ad","_type":"esindex","_id":"ITbvwWAwT9mlfV3oT3G0YA","_score":0.2936909, "_source" : 
                {"ElasticSearchIndex":{"model":"User","association_key":"15340000-0000-0000-0000-000000000007","data":"15340000-0000-0000-0000-000000000007 alan@audiologyonline.com Alan Blount AudiologyHoldings.com 502.744.4942","created":"2014-01-07 23:40:57","modified":"2014-01-07 23:40:57"}}
                }]}}

## Non-Working Attempts

		$conditions = array(
			'ElasticSearchIndex.model' => $Model->alias,
			'ElasticSearchIndex.data' => $q,
		);
		// {"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"term":{"ElasticSearchIndex.model":"User"}},{"term":{"ElasticSearchIndex.data":"alan"}}]}}}}
		// {"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
		$conditions = array(
			'bool' => array(
				'ElasticSearchIndex.model must' => $Model->alias,
				'ElasticSearchIndex.data must' => $q,
			),
		);
		// {"query":{"filtered":{"query":{"match_all":{}},"filter":{"bool":{"must":[{"term":{"ElasticSearchIndex.model":"User"}},{"term":{"ElasticSearchIndex.data":"alan"}}]}}}}}
		// {"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
		$conditions = array(
			'bool' => array(
				'ElasticSearchIndex.model must' => $Model->alias,
			),
			'query_string' => array(
				'query' => $q,
			),
		);
		// {"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"bool":{"must":[{"term":{"ElasticSearchIndex.model":"User"}}]}},{"query":{"query_string":{"query":"alan"}}}]}}}}'
		// {"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

## Working Bypass

I have put the array of direct query data into the find options (look for a pull request for this).

		$findOptions['query'] = array(
			"filtered" => array(
				"query" => array(
					"bool" => array(
						"must" => array(
							array(
								"match" => array(
									"ElasticSearchIndex.model" => $Model->alias,
								)
							),
							array(
								"match" => array(
									"ElasticSearchIndex.data" => $q,
								)
							),
						),
					),
				),
			),
		);
		// {"query":{"filtered":{"query":{"filtered":{"query":{"bool":{"must":[{"match":{"ElasticSearchIndex.model":"User"}},{"match":{"ElasticSearchIndex.data":"alan"}}]}}}}}}}

While I can get the results I need with this, it's a total bypass of what should be going on.

----------

Am I doing something wrong?

Any way we can split these functions up and make them easier to test & understand?

**Comment by josegonzalez** [comment]
I would have taken a PR for this, but it seems you've found an alternative solution :)
