### ISSUE TITLE
Undefined variable: field - Unable to Index

### ISSUE THREAD

**Issue by hm-91** [josegonzalez/cakephp-elastic-search-datasource#38]
Hi, 
I'm not able to index any model using `Elastic.elastic index`
I keep getting this below error message. 

Please advise 
Thanks

Notice Error: Undefined variable: field in [/Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php, line 793]

Notice Error: Undefined variable: field in [/Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php, line 805]

Notice Error: Undefined variable: field in [/Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php, line 826]

Warning Error: Object of class stdClass could not be converted to string in [/Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php, line 1694]

Retrieving data from mysql starting on 1970-01-01 00:00:00
Warning Error: Object of class stdClass could not be converted to string in [/Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php, line 1694]

Error: ElasticSearch Error:  Status: 400
#0 /Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php(1483): ElasticSource->_throwError(Object(stdClass))
#1 /Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php(1440): ElasticSource->_parseResponse(Object(HttpSocketResponse))
#2 /Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php(1402): ElasticSource->execute('get', 'currencies', '_count', Array)
#3 /Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php(256): ElasticSource->__call('get', Array)
#4 /Projects/ecommerce/plugins/Elastic/Model/Datasource/ElasticSource.php(256): ElasticSource->get('currencies', '_count', Array)
#5 /Projects/ecommerce/lib/Cake/Model/Model.php(3031): ElasticSource->read(Object(Currency), Array)
#6 /Projects/ecommerce/lib/Cake/Model/Model.php(3003): Model->_readDataSource('count', Array)
#7 /Projects/ecommerce/lib/Cake/Model/Model.php(2913): Model->find('count', Array)
#8 /Projects/ecommerce/lib/Cake/Model/Model.php(1818): Model->exists()
#9 /Projects/ecommerce/lib/Cake/Model/Model.php(1745): Model->_doSave(Array, Array)
#10 /Projects/ecommerce/lib/Cake/Model/Model.php(2506): Model->save(Array, Array)
#11 /Projects/ecommerce/lib/Cake/Model/Model.php(2341): Model->saveAssociated(Array, Array)
#12 /Projects/ecommerce/lib/Cake/Model/Model.php(2271): Model->saveMany(Array, Array)
#13 /Projects/ecommerce/plugins/Elastic/Console/Command/ElasticShell.php(310): Model->saveAll(Array, Array)
#14 /Projects/ecommerce/lib/Cake/Console/Shell.php(458): ElasticShell->index()
#15 /Projects/ecommerce/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('index', Array)
#16 /Projects/ecommerce/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#17 /Projects/ecommerce/app/Console/cake.php(47): ShellDispatcher::run(Array)
#18 {main}

**Comment by Hermannovich** [comment]
Hi, I have the same problem with plugin. 
I used elasticsearch 2.3.1 and cakephp 2.4.0
@josegonzalez please can you help with that issue ?
I have investigated this issue and it seems that the body of the query is not well formed for this version of elasticsearch. 
Inside the **execute** method in  **ElasticSource** source file, the query is like : 

```
array(
    'body' => '{"filtered":{"query":{"match_all":{}},"filter":{"term":{"Post.post_id":"21"}}}}'
)

```

It should be like : 

```
array(
    'body' => '{"query":{"filtered":{"query":{"match_all":{}},"filter":{"term":{"Post.post_id":"21"}}}}}'
)

```

**Comment by Hermannovich** [comment]
After reading the code I have noticed that for maintain query parent of filtered we should modify configuration from : 

```
 public $index = array(
            'datasource'     => 'Elastic.ElasticSource',
            'index'          => 'index',
            'port'           => 9200
    );
```

to 

```
 public $index = array(
            'datasource'     => 'Elastic.ElasticSource',
            'index'          => 'index',
            'port'           => 9200,
            'filteredCount'  => true
   );
```

**Comment by josegonzalez** [comment]
This plugin does not work under ES 2.x, nor do I use it in production anymore. Pull requests to documentation/the code are welcome to fix support for this new version, but I do not expect to continue maintaining the code otherwise. Sorry.

Please upgrade to CakePHP 3.x, where there is an officially supported ElasticSearch module.

**Comment by lvkhinh** [comment]
I am using cakephp ver 2.4.5 and Elastic ver 5.1.2, when I index throws error:

c:\xampp\htdocs\cake\app>Console\cake Elastic.elastic index user

Warning Error: Object of class stdClass could not be converted to string in [C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1694]

Retrieving data from mysql starting on 1970-01-01 00:00:00
Warning Error: Object of class stdClass could not be converted to string in [C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php, line 1694]

Error: ElasticSearch Error:  Status: 400
#0 C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php(1483): ElasticSource->_throwError(Object(stdClass))
#1 C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php(1440): ElasticSource->_parseResponse(Object(HttpSocketResponse))
#2 C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php(1402): ElasticSource->execute('get', 'users', '_count', Array)
#3 [internal function]: ElasticSource->__call('get', Array)
#4 C:\xampp\htdocs\cake\app\Plugin\Elastic\Model\Datasource\ElasticSource.php(256): ElasticSource->get('users', '_count', Array)
#5 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2902): ElasticSource->read(Object(User), Array)
#6 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2874): Model->_readDataSource('count', Array)
#7 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2784): Model->find('count', Array)
#8 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(1732): Model->exists()
#9 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2392): Model->save(Array, Array)
#10 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2238): Model->saveAssociated(Array, Array)
#11 C:\xampp\htdocs\cake\lib\Cake\Model\Model.php(2171): Model->saveMany(Array, Array)
#12 C:\xampp\htdocs\cake\app\Plugin\Elastic\Console\Command\ElasticShell.php(310): Model->saveAll(Array, Array)
#13 C:\xampp\htdocs\cake\lib\Cake\Console\Shell.php(431): ElasticShell->index()
#14 C:\xampp\htdocs\cake\lib\Cake\Console\ShellDispatcher.php(207): Shell->runCommand('index', Array)
#15 C:\xampp\htdocs\cake\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
#16 C:\xampp\htdocs\cake\app\Console\cake.php(36): ShellDispatcher::run(Array)
#17 {main}

**Comment by josegonzalez** [comment]
This plugin does not work under ES 2.x, nor do I use it in production anymore. Pull requests to documentation/the code are welcome to fix support for this new version, but I do not expect to continue maintaining the code otherwise. Sorry.

Please upgrade to CakePHP 3.x, where there is an officially supported ElasticSearch module.
